[project]
name = "Pholus"
version = "1.0"
requires-python = "= 2.7.18"
dependencies = [
"requests",
"scapy"
]

[tool.setuptools]
py-modules = ["pholus", "pholus3"]

[project.scripts]
pholus3 = "pholus3:main"
pholus = "pholus:main"
