[project]
name = "Pholus"
version = "1.0"
dependencies = [
"requests",
"argparse",
"re",
"binascii",
"multiprocessing",
"logging",
"itertools",
"scapy",
"itertools",
"codecs",
"ipaddress",
]

[project.scripts]
pholus3 = "pholus3:main",
pholus = "pholus:main"
