[project]
name = "Pholus"
version = "1.0"
dependencies = [
"requests",
"re",
"binascii",
"multiprocessing",
"logging",
"itertools",
"scapy",
"itertools",
"codecs",
"ipaddress",
]

[tool.setuptools]
py-modules = []

[project.scripts]
pholus3 = "pholus3:main"
pholus = "pholus:main"
